const FOOD_KEY="km_html_foods_v11";const SHOPPING_KEY="km_html_shopping_v11";const THEME_KEY="km_html_dark_v11";
const demoFoods=[{id:"1",barcode:"4012345678901",name:"Milch",category:"Milchprodukte",amount:1,unit:"l",minAmount:1,expiry:todayOffset(0),location:"Kühlschrank",note:"Heute verbrauchen"},{id:"2",barcode:"4012345678902",name:"Joghurt",category:"Milchprodukte",amount:2,unit:"Becher",minAmount:2,expiry:todayOffset(1),location:"Kühlschrank",note:""},{id:"3",barcode:"4012345678903",name:"Salat",category:"Gemüse",amount:1,unit:"Stück",minAmount:1,expiry:todayOffset(2),location:"Kühlschrank",note:""},{id:"4",barcode:"4012345678904",name:"Käse",category:"Milchprodukte",amount:250,unit:"g",minAmount:150,expiry:todayOffset(3),location:"Kühlschrank",note:""},{id:"5",barcode:"4012345678905",name:"Eier",category:"Sonstiges",amount:2,unit:"Stück",minAmount:6,expiry:todayOffset(5),location:"Kühlschrank",note:"Fast leer"}];
const demoShopping=[{id:"s1",name:"Milch",amount:"1 l",checked:true},{id:"s2",name:"Butter",amount:"250 g",checked:false},{id:"s3",name:"Tomaten",amount:"500 g",checked:false}];
const productDatabase={"4012345678901":{name:"Milch",category:"Milchprodukte",unit:"l",amount:1,minAmount:1,location:"Kühlschrank"},"4012345678902":{name:"Joghurt",category:"Milchprodukte",unit:"Becher",amount:1,minAmount:2,location:"Kühlschrank"},"4012345678903":{name:"Salat",category:"Gemüse",unit:"Stück",amount:1,minAmount:1,location:"Kühlschrank"},"4012345678904":{name:"Käse",category:"Milchprodukte",unit:"g",amount:250,minAmount:150,location:"Kühlschrank"},"4012345678905":{name:"Eier",category:"Sonstiges",unit:"Stück",amount:6,minAmount:6,location:"Kühlschrank"}};
let foods=load(FOOD_KEY,demoFoods);let shopping=load(SHOPPING_KEY,demoShopping);let stream=null;let scanTimer=null;let lastBarcode="";
function load(k,f){const d=localStorage.getItem(k);return d?JSON.parse(d):f}function save(){localStorage.setItem(FOOD_KEY,JSON.stringify(foods));localStorage.setItem(SHOPPING_KEY,JSON.stringify(shopping))}function todayOffset(o){return new Date(Date.now()+o*86400000).toISOString().slice(0,10)}function daysUntil(s){const t=new Date(),d=new Date(s);t.setHours(0,0,0,0);d.setHours(0,0,0,0);return Math.round((d-t)/86400000)}function expiryText(days){if(days<0)return"abgelaufen";if(days===0)return"Heute";if(days===1)return"1 Tag";return days+" Tage"}function iconFor(c){return {"Milchprodukte":"🥛","Fleisch / Wurst":"🥩","Gemüse":"🥬","Obst":"🍎","Getränke":"🥤","Vorrat":"🥫","Sonstiges":"📦"}[c]||"📦"}
function render(){document.getElementById("today").textContent=new Date().toLocaleDateString("de-DE",{weekday:"long",year:"numeric",month:"long",day:"numeric"});const soon=foods.filter(f=>daysUntil(f.expiry)<=3).sort((a,b)=>daysUntil(a.expiry)-daysUntil(b.expiry));const low=foods.filter(f=>Number(f.amount)<=Number(f.minAmount));const expired=foods.filter(f=>daysUntil(f.expiry)<0);soonCount.textContent=soon.length;lowCount.textContent=low.length;totalCount.textContent=foods.length;shoppingCount.textContent=shopping.length;statTotal.textContent=foods.length;statExpired.textContent=expired.length;statLow.textContent=low.length;statShopping.textContent=shopping.length;renderList("soonList",soon,"expiry");renderList("lowList",low,"stock");renderShopping();renderFoods()}
function renderList(id,list,mode){const el=document.getElementById(id);if(!list.length){el.innerHTML='<div class="empty">Keine Einträge vorhanden.</div>';return}el.innerHTML=list.map(item=>{const days=daysUntil(item.expiry);const pillClass=days<=0?"red":days<=3?"orange":"green";const right=mode==="stock"?`${item.amount} ${item.unit}`:expiryText(days);return `<div class="row"><div class="thumb">${iconFor(item.category)}</div><div><strong>${item.name}</strong><small>${item.location}</small></div><span class="pill ${pillClass}">${right}</span></div>`}).join("")}
function renderShopping(){const el=document.getElementById("shoppingList");if(!shopping.length){el.innerHTML='<div class="empty">Einkaufsliste ist leer.</div>';return}el.innerHTML=shopping.map(item=>`<label class="shopping-row"><input type="checkbox" ${item.checked?"checked":""} onchange="toggleShopping('${item.id}')"><span>${item.name}</span><small>${item.amount||""}</small><button class="delete-btn" onclick="deleteShopping('${item.id}')" type="button">×</button></label>`).join("")}
function renderFoods(){const search=document.getElementById("search").value.toLowerCase();const el=document.getElementById("foodList");const filtered=foods.filter(item=>`${item.name} ${item.category} ${item.location} ${item.barcode||""}`.toLowerCase().includes(search)).sort((a,b)=>daysUntil(a.expiry)-daysUntil(b.expiry));if(!filtered.length){el.innerHTML='<div class="empty">Keine Lebensmittel gefunden.</div>';return}el.innerHTML=filtered.map(item=>{const days=daysUntil(item.expiry);return `<article class="food-card"><div class="thumb">${iconFor(item.category)}</div><div><h3>${item.name}</h3><p>${item.category} · ${item.location}</p><small>${item.amount} ${item.unit} · Ablauf: ${expiryText(days)}${item.barcode?" · Barcode: "+item.barcode:""}</small></div><button class="delete-btn" onclick="deleteFood('${item.id}')" type="button">🗑</button></article>`}).join("")}
foodForm.addEventListener("submit",e=>{e.preventDefault();foods.push({id:crypto.randomUUID(),barcode:barcodeInput.value.trim(),name:name.value.trim(),category:category.value,amount:Number(amount.value),unit:unit.value.trim(),minAmount:Number(minAmount.value),expiry:expiry.value,location:location.value,note:note.value.trim()});e.target.reset();amount.value=1;minAmount.value=1;unit.value="Stück";barcodeInput.value="";save();render()});
shoppingForm.addEventListener("submit",e=>{e.preventDefault();const n=shoppingName.value.trim();if(!n)return;shopping.push({id:crypto.randomUUID(),name:n,amount:"",checked:false});shoppingName.value="";save();render()});barcodeForm.addEventListener("submit",e=>{e.preventDefault();const b=barcodeInput.value.trim();if(b)applyBarcode(b)});search.addEventListener("input",renderFoods);themeBtn.addEventListener("click",toggleTheme);openScannerTop.addEventListener("click",()=>{scanner.scrollIntoView({behavior:"smooth"});startScanner()});startScanBtn.addEventListener("click",startScanner);stopScanBtn.addEventListener("click",stopScanner);
function toggleTheme(){app.classList.toggle("dark");const d=app.classList.contains("dark");localStorage.setItem(THEME_KEY,d?"1":"0");themeBtn.textContent=d?"☀️ Light Mode":"🌙 Dark Mode"}function deleteFood(id){foods=foods.filter(i=>i.id!==id);save();render()}function toggleShopping(id){shopping=shopping.map(i=>i.id===id?{...i,checked:!i.checked}:i);save();render()}function deleteShopping(id){shopping=shopping.filter(i=>i.id!==id);save();render()}
async function startScanner(){const result=scanResult,video=scannerVideo,placeholder=scannerPlaceholder;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){result.textContent="Kamera wird von diesem Browser nicht unterstützt. Bitte Barcode manuell eingeben.";return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});video.srcObject=stream;await video.play();video.style.display="block";placeholder.style.display="none";result.textContent="Scanner läuft. Barcode vor die Kamera halten.";if("BarcodeDetector" in window){const detector=new BarcodeDetector({formats:["ean_13","ean_8","code_128","upc_a","upc_e"]});scanTimer=setInterval(async()=>{try{const codes=await detector.detect(video);if(codes.length>0){const value=codes[0].rawValue;if(value&&value!==lastBarcode){lastBarcode=value;barcodeInput.value=value;applyBarcode(value);stopScanner()}}}catch(err){result.textContent="Scannen nicht möglich. Bitte manuelle Eingabe verwenden."}},700)}else result.textContent="Kamera aktiv. Automatische Barcode-Erkennung wird in diesem Browser nicht unterstützt. Bitte Barcode manuell eingeben."}catch(e){result.textContent="Kamera konnte nicht gestartet werden. Auf GitHub Pages muss die Seite über HTTPS geöffnet sein."}}
function stopScanner(){if(scanTimer){clearInterval(scanTimer);scanTimer=null}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}scannerVideo.pause();scannerVideo.srcObject=null;scannerVideo.style.display="none";scannerPlaceholder.style.display="grid"}
function applyBarcode(barcode){const product=productDatabase[barcode];barcodeInput.value=barcode;if(product){name.value=product.name;category.value=product.category;amount.value=product.amount;unit.value=product.unit;minAmount.value=product.minAmount;location.value=product.location;scanResult.textContent=`Barcode erkannt: ${barcode} – ${product.name}. Bitte Ablaufdatum eintragen und speichern.`}else{scanResult.textContent=`Barcode übernommen: ${barcode}. Artikel bitte manuell ergänzen.`;name.focus()}add.scrollIntoView({behavior:"smooth"})}
if(localStorage.getItem(THEME_KEY)==="1"){app.classList.add("dark");themeBtn.textContent="☀️ Light Mode"}render();
